spring.config.import=optional:file:../.env[.properties]
server.port=${NOTIFICATION_PORT:5460}

spring.application.name=notification-service


logging.level.root=${LOG_LEVEL:INFO}
logging.level.com.prakhar=${LOG_LEVEL:INFO}

# DB Exclude
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
