spring.config.import=optional:file:../.env[.properties]
server.port=${CORE_TRADING_PORT:5456}

spring.application.name=core-trading-service

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost/trading}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

# HikariCP Settings for Neon (Lower connection limits)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASS}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=core-trading-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.prakhar.*
spring.kafka.consumer.properties.spring.json.use.type.headers=true

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

razorpay.key.id=${RAZORPAY_KEY_ID:changeme}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:changeme}

wallet.signup-bonus=${SIGNUP_BONUS_AMOUNT:10000}
simulator.exchange-rate=${SIMULATOR_EXCHANGE_RATE:10000}
internal.service.api.key=${INTERNAL_SERVICE_API_KEY:changeme}

feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000

logging.level.root=${LOG_LEVEL:INFO}
logging.level.com.prakhar=${LOG_LEVEL:INFO}
