server.port=${GATEWAY_PORT:8081}

spring.config.import=optional:file:../.env[.properties]
spring.application.name=api-gateway

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**


# User Service (Auth Service)
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[1].filters[0]=JwtValidationFilter


eureka.client.service-url.defaultZone=${EUREKA_URL}

jwt.secret=${JWT_SECRET}
internal.service.api.key=${INTERNAL_SERVICE_API_KEY}

logging.level.root=${LOG_LEVEL:INFO}
logging.level.com.prakhar=${LOG_LEVEL:INFO}

spring.main.web-application-type=reactive

# CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600
