spring.config.import=optional:file:../.env[.properties]
server.port=${GATEWAY_PORT:8081}

spring.application.name=api-gateway

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Core Trading Service
spring.cloud.gateway.routes[1].id=core-trading-service
spring.cloud.gateway.routes[1].uri=lb://core-trading-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**,/api/wallet/**,/api/assets/**,/api/withdrawal/**,/api/admin/**,/api/payment-details/**,/api/portfolio/**

# Market AI Service
spring.cloud.gateway.routes[2].id=market-ai-service
spring.cloud.gateway.routes[2].uri=lb://market-ai-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/coins/**,/api/market/**,/api/chat/**

# User Service (Auth Service)
spring.cloud.gateway.routes[3].id=user-service
spring.cloud.gateway.routes[3].uri=lb://auth-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/users/**

# Razorpay Webhook (No JWT)
spring.cloud.gateway.routes[4].id=razorpay-webhook
spring.cloud.gateway.routes[4].uri=lb://core-trading-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/wallet/webhook/razorpay

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

jwt.secret=${JWT_SECRET:changeme}
INTERNAL_SERVICE_API_KEY=${INTERNAL_SERVICE_API_KEY:changeme}

logging.level.root=${LOG_LEVEL:INFO}
logging.level.com.prakhar=${LOG_LEVEL:INFO}

spring.main.web-application-type=reactive

# DB Exclude
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600
