spring.config.import=optional:file:../.env[.properties]
server.port=${MARKET_AI_PORT:5455}

spring.application.name=market-ai-service

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASS}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

coingecko.api.key=${COINGECKO_API_KEY:}
coingecko.base-url=${COINGECKO_BASE_URL:https://api.coingecko.com/api/v3}
internal.service.api.key=${INTERNAL_SERVICE_API_KEY:changeme}

gemini.api.key=${GEMINI_API_KEY:changeme}
gemini.api-url=${GEMINI_AI_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent}

logging.level.root=${LOG_LEVEL:INFO}
logging.level.com.prakhar=${LOG_LEVEL:INFO}

# DB Exclude
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
